version: "3.9"  # optional since v1.27.0
services:
  web: node . --db "mongodb+srv://Ikhsan65:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
